#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dtest=false \
    -Dsystemd=disabled \
    -Ddbus=enabled \
    -Dzeroconf=disabled \
    -Dalsa=enabled \
    output

ninja -C output
ninja -C output install
