#!/bin/sh -e

patch -p1 < no-perl.patch

make oldconfig
make syncconfig

make
make INSTALL_MOD_PATH="$1" INSTALL_MOD_STRIP=1 modules_install

mkdir -p "$1/boot"
cp arch/x86/boot/bzImage "$1/boot/vmlinuz-kiss"
rm -f "$1/lib/modules"/*/build "$1/lib/modules"/*/source
