#!/bin/sh -e

make
make PREFIX="/usr" DESTDIR="$1" install

# Install runit service.
mkdir -p "$1/etc/sv/sdhcp"
cp -f sdhcp.run "$1/etc/sv/sdhcp/run"
ln -sf /run/runit/supervise.sdhcp "$1/etc/sv/sdhcp/supervise"
