#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsystemd-user-unit-dir=/usr/lib/systemd/user \
    -Dwallpaper=disabled \
    -Dsettings=disabled \
    -Dappchooser=enabled \
    -Dlockdown=disabled \
    output

ninja -C output
ninja -C output install

rm -rf "$DESTDIR"/usr/lib/systemd
