#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-vla.patch

meson setup \
	--prefix=/usr \
	--libexecdir=/usr/lib \
	-Dsystemd=disabled \
	-Dsd-bus-provider=basu \
	output

ninja -C output
ninja -C output install

install -Dm644 wlr-portals.conf "$1/usr/share/xdg-desktop-portal/wlr-portals.conf"
