#!/bin/sh -e

# Allow undefined symbol versions for LLVM/lld compatibility.
export LDFLAGS="$LDFLAGS -Wl,--undefined-version"

# Disable HTML documentation.
sed 's/html man/man/' doc/Makefile.in > _
mv -f _ doc/Makefile.in

./configure \
    ac_cv_lib_ncurses_initscr=no \
    ac_cv_lib_curses_initscr=no \
    --prefix=/usr \
    --enable-shared \
    --disable-gtktest

make
make DESTDIR="$1" install
