#!/bin/sh

dir="/var/cache/backlight"

[ -d "$dir" ] || mkdir -p "$dir"
[ -w "$dir" ] || chmod 755 "$dir"

# Save current brightness of each card.
for card in $(find /sys/class/backlight/ -type l); do
    cp "$card/brightness" "$dir/$(basename $card)-brightness-old"
done
