#!/bin/sh

dir="/var/cache/backlight"

# Restore saved brightness for each card, if any.
for card in $(find /sys/class/backlight/ -type l); do
    storage_file="$dir/$(basename $card)-brightness-old"
    [ -r "$storage_file" ] && cp "$storage_file" "$card/brightness"
done

chpst backlight pause
exec sleep infinity
