#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddbus=enabled \
    -Dbluez5=enabled \
    -Dsndfile=enabled \
    -Djack=disabled \
    -Dpipewire-jack=disabled \
    -Dtests=disabled \
    -Dudev=enabled \
    -Dudevrulesdir=/usr/lib/udev/rules.d \
    -Dsession-managers=wireplumber \
    -Dwireplumber:system-lua=true \
    . output

ninja -C output
ninja -C output install

cp -r subprojects/wireplumber/src/config/wireplumber.conf.d/* \
    "$1/usr/share/wireplumber/wireplumber.conf.d/" 2>/dev/null || true
