#!/bin/sh -e

export DESTDIR="$1"

sed -i '/test-.*'/d meson.build

meson setup \
    -Dudev=enabled \
    -Dinstalled_tests=false \
    -Dgtk_doc=false \
    -Ddesktop_docs=false \
    -Dbuild_gtk4=false \
    -Ddebug_tools=false \
    -Dintrospection=false \
    -Dsystemd=disabled \
    -Dlegacy_library=false \
    output

ninja -C output
ninja -C output install
