#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

for patch in readline83-0* ; do
    patch -p0 < "$patch"
done

patch -p1 < shlib.patch

./configure \
    --prefix=/usr \
    --enable-shared

make SHLIB_LIBS="-lncurses"
make DESTDIR="$1" install

rmdir "$1/usr/bin"
