#!/bin/sh -e

patch -p1 < m4-hand-written-lexer.patch

export MAKEFLAGS=-j1

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-m4 \
    --enable-static

make
make DESTDIR="$1" install
