#!/bin/sh -e

for dir in amdgpu amd-ucode amd rtw88; do
  mkdir -p "$1/usr/lib/firmware/$dir"
done

cp -r amdgpu/renoir_*                     "$1/usr/lib/firmware/amdgpu"
cp -r rtw88/rtw8822c_*                    "$1/usr/lib/firmware/rtw88"
cp -r amd-ucode/microcode_amd_fam17h.bin  "$1/usr/lib/firmware/amd-ucode"
cp -r amd/amd_sev_fam17h_model0xh.sbin    "$1/usr/lib/firmware/amd"
